Repository HackerExperience/HEBorn, pull requests merged in 2018-02, with the labels that each got.

#446 Fix WindowManager pinned window edge cases.
  src/OS/WindowManager/Config.elm
  src/OS/WindowManager/Helpers.elm
  src/OS/WindowManager/Launch.elm
  src/OS/WindowManager/Messages.elm
  src/OS/WindowManager/Models.elm
  src/OS/WindowManager/Subscriptions.elm
  src/OS/WindowManager/Update.elm
  src/OS/WindowManager/View.elm
Labels: Kind:Enhancement, Priority:High

#449 Finally add pinned windows.
  src/Css/Icons.elm
  src/OS/WindowManager/Config.elm
  src/OS/WindowManager/Dock/Config.elm
  src/OS/WindowManager/Dock/View.elm
  src/OS/WindowManager/Messages.elm
  src/OS/WindowManager/Models.elm
  src/OS/WindowManager/Resources.elm
  src/OS/WindowManager/Style.elm
  src/OS/WindowManager/Update.elm
  src/OS/WindowManager/View.elm
Labels: Kind:Feature, Pending approval, Priority:Intermediate

#451 Small fixes
  src/Apps/Browser/Pages/Home/Config.elm
  src/Apps/Calculator/View.elm
  src/Apps/Email/Config.elm
  src/Apps/FloatingHeads/Config.elm
  src/Apps/FloatingHeads/Launch.elm
  src/Apps/FloatingHeads/Messages.elm
  src/Apps/FloatingHeads/Update.elm
  src/Core/Update.elm
  src/Decoders/Storyline.elm
  src/Game/Storyline/DynamicStyle.elm
  src/Game/Storyline/Models.elm
  src/Game/Storyline/Shared.elm
  src/Game/Storyline/StepActions/Helper.elm
  src/Game/Web/Requests/DNS.elm
  src/OS/WindowManager/Config.elm
  src/OS/WindowManager/Helpers.elm
  src/OS/WindowManager/Launch.elm
  src/OS/WindowManager/Models.elm
  src/OS/WindowManager/Update.elm
  src/OS/WindowManager/View.elm
Labels: Kind:Enhancement, Priority:High

#455 Fixes some visual behaviours
  elm-package.json
  src/Apps/BackFlix/Models.elm
  src/Apps/BounceManager/Models.elm
  src/Apps/Browser/Models.elm
  src/Apps/Calculator/Models.elm
  src/Apps/Email/Models.elm
  src/Apps/Shared.elm
  src/Core/Config.elm
  src/Core/Update.elm
  src/OS/Config.elm
  src/OS/Header/AccountView.elm
  src/OS/Header/Config.elm
  src/OS/Header/ConnectionBarView.elm
  src/OS/Header/NotificationsView.elm
  src/OS/Header/TaskbarView.elm
  src/OS/Header/View.elm
  src/OS/Resources.elm
  src/OS/Style.elm
  src/OS/View.elm
  src/OS/WindowManager/Messages.elm
  src/OS/WindowManager/Models.elm
  src/OS/WindowManager/Subscriptions.elm
  src/OS/WindowManager/Update.elm
  src/OS/WindowManager/View.elm
  tests/elm-package.json
Labels: Kind:Feature, Priority:Intermediate
