Repository HackerExperience/HEBorn, pull requests merged in 2018-03, with the labels that each got.

#457 Remove Header dependency on Servers.
  src/Game/Account/Finances/Messages.elm
  src/Game/Account/Finances/Requests/Login.elm
  src/Game/Account/Finances/Requests/Transfer.elm
  src/Game/Account/Finances/Update.elm
  src/Game/Servers/Models.elm
  src/OS/Config.elm
  src/OS/Header/AccountView.elm
  src/OS/Header/Config.elm
  src/OS/Header/ConnectionBarView.elm
  src/OS/WindowManager/Models.elm
Labels: Kind:Chore, Priority:Low

#454 Virus app
  src/Apps/BounceManager/View.elm
  src/Apps/DBAdmin/Tabs/Servers/Helpers.elm
  src/Apps/DBAdmin/Tabs/Servers/View.elm
  src/Apps/DBAdmin/View.elm
  src/Apps/Shared.elm
  src/Apps/Style.elm
  src/Apps/VirusPanel/Config.elm
  src/Apps/VirusPanel/Messages.elm
  src/Apps/VirusPanel/Models.elm
  src/Apps/VirusPanel/Resources.elm
  src/Apps/VirusPanel/Style.elm
  src/Apps/VirusPanel/Update.elm
  src/Apps/VirusPanel/View.elm
  src/Core/Config.elm
  src/Decoders/Account.elm
  src/Decoders/Bounces.elm
  src/Decoders/Database.elm
  src/Decoders/Finances.elm
  src/Decoders/Processes.elm
  src/Events/Account/Config.elm
  src/Events/Account/Handler.elm
  src/Events/Account/Handlers/VirusCollected.elm
  src/Game/Account/Bounces/Dummy.elm
  src/Game/Account/Bounces/Models.elm
  src/Game/Account/Bounces/Requests/Create.elm
  src/Game/Account/Bounces/Requests/Update.elm
  src/Game/Account/Config.elm
  src/Game/Account/Database/Config.elm
  src/Game/Account/Database/Dummy.elm
  src/Game/Account/Database/Messages.elm
  src/Game/Account/Database/Models.elm
  src/Game/Account/Database/Requests/CollectWithBank.elm
  src/Game/Account/Database/Shared.elm
  src/Game/Account/Database/Update.elm
  src/Game/Account/Dock/Models.elm
  src/Game/Account/Finances/Dummy.elm
  src/Game/Account/Finances/Models.elm
  src/Game/Meta/Types/Apps/Desktop.elm
  src/Game/Servers/Processes/Models.elm
  src/OS/WindowManager/Config.elm
  src/OS/WindowManager/Dock/Style.elm
  src/OS/WindowManager/Launch.elm
  src/OS/WindowManager/Messages.elm
  src/OS/WindowManager/Models.elm
  src/OS/WindowManager/Update.elm
  src/OS/WindowManager/View.elm
  src/Requests/Topics.elm
  src/UI/Widgets/Modal.elm
  src/UI/Widgets/Modal/Virus.elm
Labels: Kind:Feature

#461 Fix BackFlix API
  src/Apps/BackFlix/Config.elm
  src/Apps/BackFlix/Models.elm
  src/Apps/BackFlix/View.elm
  src/Game/BackFlix/Models.elm
  src/Game/BackFlix/Update.elm
  src/OS/Config.elm
  src/OS/Console/Config.elm
  src/OS/Console/View.elm
  src/OS/WindowManager/Config.elm
Labels: Kind:Chore

#460 Fix BounceManager
  src/Apps/BounceManager/Resources.elm
  src/Apps/BounceManager/Style.elm
  src/Apps/BounceManager/Update.elm
  src/Apps/BounceManager/View.elm
  src/Apps/DBAdmin/Tabs/Servers/Helpers.elm
  src/Apps/DBAdmin/Tabs/Servers/View.elm
  src/Apps/VirusPanel/View.elm
  src/Game/Account/Database/Models.elm
Labels: Kind:Bug

#462 Move Header and Console Styles to their respective files
  src/Core/Stylesheets.elm
  src/OS/Console/Resources.elm
  src/OS/Console/Style.elm
  src/OS/Console/View.elm
  src/OS/Header/AccountView.elm
  src/OS/Header/ConnectionBarView.elm
  src/OS/Header/NetworkView.elm
  src/OS/Header/NotificationsView.elm
  src/OS/Header/Resources.elm
  src/OS/Header/Style.elm
  src/OS/Header/TaskbarView.elm
  src/OS/Header/View.elm
  src/OS/Resources.elm
  src/OS/Style.elm
  src/OS/Toasts/Resources.elm
  src/OS/Toasts/Style.elm
  src/OS/Toasts/View.elm
  src/UI/DynStyles/Highlight/OS.elm
Labels: Kind:Enhancement

#466 Add support to launch BounceManager with params
  src/Apps/BounceManager/Launch.elm
  src/Apps/BounceManager/Messages.elm
  src/Apps/BounceManager/Models.elm
  src/Apps/BounceManager/Shared.elm
  src/Apps/BounceManager/Update.elm
  src/Apps/Params.elm
  src/OS/Config.elm
  src/OS/Header/Config.elm
  src/OS/Header/ConnectionBarView.elm
Labels: Work In Progress

#465 Change scrollbar behavior in Apps
  src/Apps/Browser/Config.elm
  src/Apps/Browser/Style.elm
  src/Apps/ServersGears/Style.elm
  src/UI/Style.elm
Labels: Kind:Bug

#463 Add await event.
  src/Core/Config.elm
  src/Core/Messages.elm
  src/Core/Models.elm
  src/Core/Update.elm
  src/Driver/Websocket/Config.elm
  src/Driver/Websocket/Update.elm
  src/Events/Handler.elm
  src/Game/Meta/Types/AwaitEvent.elm
  src/OS/Config.elm
  src/OS/WindowManager/Config.elm
  tests/TestUtils.elm
Labels: Kind:Chore, Priority:High

#471 Improve AwaitEvents System
  src/Apps/BounceManager/Config.elm
  src/Apps/BounceManager/Launch.elm
  src/Apps/BounceManager/Messages.elm
  src/Apps/BounceManager/Models.elm
  src/Apps/BounceManager/Update.elm
  src/Apps/BounceManager/View.elm
  src/Apps/Shared.elm
  src/Apps/VirusPanel/Config.elm
  src/Core/Messages.elm
  src/Core/Update.elm
  src/Game/Account/Bounces/Requests/Create.elm
  src/Game/Account/Bounces/Requests/Update.elm
  src/Game/Account/Bounces/Shared.elm
  src/Game/Meta/Types/AwaitEvent.elm
  src/Game/Servers/Processes/Models.elm
  src/Game/Servers/Processes/Update.elm
  src/OS/Config.elm
  src/OS/WindowManager/Config.elm
  src/Utils/Model/RandomUuid.elm
Labels: Kind:Enhancement

#478 Fix Process decoding
  src/Apps/TaskManager/Config.elm
  src/Apps/TaskManager/View.elm
  src/Decoders/Processes.elm
  src/Events/Server/Handlers/ProcessBruteforceFailed.elm
  src/Events/Server/Handlers/ProcessCompleted.elm
  src/Events/Server/Handlers/ProcessCreated.elm
  src/Game/Servers/Processes/Messages.elm
  src/Game/Servers/Processes/Models.elm
  src/Game/Servers/Processes/Shared.elm
  src/Game/Servers/Processes/Update.elm
  tests/Game/Servers/Processes/IntegrationTest.elm
  tests/Gen/Processes.elm
Labels: Kind:Bug

#480 Implement Upload
  src/Apps/Explorer/Config.elm
  src/Apps/Explorer/View.elm
  src/Decoders/Processes.elm
  src/Game/Servers/Config.elm
  src/Game/Servers/Notifications/Messages.elm
  src/Game/Servers/Notifications/Shared.elm
  src/Game/Servers/Notifications/Update.elm
  src/Game/Servers/Processes/Config.elm
  src/Game/Servers/Processes/Messages.elm
  src/Game/Servers/Processes/Models.elm
  src/Game/Servers/Processes/Requests/Upload.elm
  src/Game/Servers/Processes/Update.elm
  src/OS/WindowManager/Config.elm
  src/Requests/Topics.elm
Labels: Kind:Feature

#473 Implement Database bootstrap decoding
  src/Apps/BounceManager/Models.elm
  src/Apps/BounceManager/Update.elm
  src/Apps/BounceManager/View.elm
  src/Apps/DBAdmin/Messages.elm
  src/Apps/DBAdmin/Models.elm
  src/Apps/DBAdmin/Tabs/Servers/Helpers.elm
  src/Apps/DBAdmin/Tabs/Servers/View.elm
  src/Apps/DBAdmin/Update.elm
  src/Apps/DBAdmin/View.elm
  src/Apps/VirusPanel/Models.elm
  src/Apps/VirusPanel/Update.elm
  src/Apps/VirusPanel/View.elm
  src/Css/Utils.elm
  src/Decoders/Account.elm
  src/Decoders/Database.elm
  src/Game/Account/Bounces/Dummy.elm
  src/Game/Account/Database/Dummy.elm
  src/Game/Account/Database/Models.elm
  src/Game/Account/Database/Update.elm
  src/Game/Account/Finances/Dummy.elm
  src/UI/Style.elm
  src/UI/Widgets/Modal.elm
  src/UI/Widgets/Modal/Virus.elm
  src/UI/Widgets/Spinner.elm
Labels: Kind:Enhancement

#483 Fix Open Remote Desktop
  src/Apps/Browser/Config.elm
  src/Apps/Browser/Pages/Configs.elm
  src/Apps/Browser/Pages/DownloadCenter/Config.elm
  src/Apps/Browser/Pages/DownloadCenter/View.elm
  src/Apps/Browser/Pages/Webserver/Config.elm
  src/Apps/Browser/Pages/Webserver/View.elm
  src/Apps/Browser/Widgets/HackingPanel/View.elm
  src/OS/WindowManager/Config.elm
Labels: Kind:Bug

#484 Add clickable nodes to Bounce Menu
  src/Apps/Browser/Launch.elm
  src/Apps/Browser/Messages.elm
  src/Apps/Browser/Models.elm
  src/Apps/Browser/Shared.elm
  src/Apps/Browser/Update.elm
  src/Apps/FloatingHeads/Config.elm
  src/Apps/Params.elm
  src/OS/Header/ConnectionBarView.elm
  tests/Gen/Browser.elm
Labels: Kind:Feature

#482 Fix Bounce Manager when changing tabs
  src/Apps/BounceManager/Update.elm
Labels: Kind:Bug

#487 Fix progress-bar
  src/Apps/TaskManager/View.elm
Labels: Kind:Bug, Priority:High

#486 Fix 'password_acquired' kill 'process_created' event
  src/Core/Config.elm
  src/Events/Account/Handlers/ServerPasswordAcquired.elm
  src/Events/Server/Config.elm
  src/Events/Server/Handler.elm
  src/Events/Server/Handlers/ProcessCreated.elm
  src/Events/Server/Handlers/ProcessesRecalcado.elm
  src/Game/Account/Database/Update.elm
  src/Game/Servers/Processes/Messages.elm
  src/Game/Servers/Processes/Update.elm
  tests/Game/Servers/Processes/IntegrationTest.elm
Labels: Kind:Bug

#489 Fix BounceManager save behaviour
  src/Apps/BounceManager/Config.elm
  src/Apps/BounceManager/Messages.elm
  src/Apps/BounceManager/Models.elm
  src/Apps/BounceManager/Resources.elm
  src/Apps/BounceManager/Style.elm
  src/Apps/BounceManager/Update.elm
  src/Apps/BounceManager/View.elm
  src/Core/Config.elm
  src/Decoders/Bounces.elm
  src/Driver/Websocket/Update.elm
  src/Events/Account/Config.elm
  src/Events/Account/Handler.elm
  src/Events/BackFlix/Handler.elm
  src/Events/Handler.elm
  src/Events/Server/Handler.elm
  src/Game/Account/Bounces/Config.elm
  src/Game/Account/Bounces/Messages.elm
  src/Game/Account/Bounces/Models.elm
  src/Game/Account/Bounces/Update.elm
  src/Game/Account/Config.elm
  src/Game/BackFlix/Messages.elm
  src/Game/BackFlix/Update.elm
  src/Game/Config.elm
  src/Game/Models.elm
  src/OS/Header/ConnectionBarView.elm
  src/OS/WindowManager/Config.elm
  src/UI/Elements/Modal.elm
  src/UI/Elements/Modal/Virus.elm
Labels: Kind:Bug

#488 Expand Storyline to include NastyVirus sub-chapter
  src/Decoders/Storyline.elm
  src/Game/Storyline/Emails/View.elm
  src/Game/Storyline/Requests/Reply.elm
  src/Game/Storyline/Shared.elm
Labels: Priority:High
